example:
  filename: example
  class: BehaviorExample
  params:
    alpha: 1.0
    beta: 2.0

goto_xy:
  filename: goto_xy
  class: GoToXY
  params:
    x: 25.0
    y: 25.0

circle:
  filename: circle
  class: CircleBehavior
  params:
    radius: 50.0
    spacing: 10