mavros:
  ros__parameters: {}

mavros_router:
  ros__parameters: {}

mavros_node:
  ros__parameters:
    fcu_url: "/dev/ttyUSB0:921600"

/**:
  ros__parameters:
    plugin_denylist: [odometry]
    # plugin_allowlist: []
